export const DoctorList = [
  {
    id: 112,
    name: "Abhay Rana",
    expertise: "Obstetricians",
    city: "Delhi",
  },
  {
    id: 113,
    name: "Surbhi Chouhan",
    expertise: "Neurologist",
    city: "Mumbai",
  },
  {
    id: 114,
    name: "Vaishali Sharma",
    expertise: "Obstetricians",
    city: "Ahemdabad",
  },
  {
    id: 115,
    name: "Rajat Kansal",
    expertise: "Neurologist",
    city: "Delhi",
  },
  {
    id: 116,
    name: "Megha Pundir",
    expertise: "Diabetologist",
    city: "Ahemdabad",
  },
  {
    id: 117,
    name: "Sumit Jain",
    expertise: "Obstetricians",
    city: "Mumbai",
  },
  {
    id: 118,
    name: "Vikram Gupta",
    expertise: "Diabetologist",
    city: "Banglore",
  },
  {
    id: 119,
    name: "Azam Khan",
    expertise: "Obstetricians",
    city: "Delhi",
  },
  {
    id: 120,
    name: "Radhika Singh",
    expertise: "Obstetricians",
    city: "Surat",
  },
  {
    id: 121,
    name: "VK choudhary",
    expertise: "Diabetologist",
    city: "Surat",
  },
  {
    id: 122,
    name: "Hanzala Azam",
    expertise: "Diabetologist",
    city: "Banglore",
  },
  {
    id: 123,
    name: "Kapil Saini",
    expertise: "Neurologist",
    city: "Delhi",
  },
  {
    id: 124,
    name: "Chakshu Kumar",
    expertise: "Oncology",
    city: "Pune",
  },
  {
    id: 125,
    name: "Ramsha Siddiqui",
    expertise: "Dermatologist",
    city: "kolkata",
  },
  {
    id: 126,
    name: "KaramPreet Singh",
    expertise: "Oncology",
    city: "Delhi",
  },
  {
    id: 127,
    name: "Sunil Setty",
    expertise: "Neurologist",
    city: "Delhi",
  },
  {
    id: 128,
    name: "Abhinav Bansal",
    expertise: "Dentist",
    city: "Delhi",
  },
  {
    id: 129,
    name: "SD Jain",
    expertise: "Dermatologist",
    city: "Pune",
  },
  {
    id: 130,
    name: "Dev Rana",
    expertise: "Dentist",
    city: "Hyderabad",
  },
  {
    id: 131,
    name: "Anjali Gupta",
    expertise: "Obstetricians",
    city: "Delhi",
  },
  {
    id: 132,
    name: "Shivangi Joshi",
    expertise: "Sports Medicine",
    city: "Hyderabad",
  },
];
